### ISSUE TITLE
New python module request for cyhy-core docker image

### ISSUE THREAD

**Issue by st0rmbl3ss3d** [cisagov/cyhy-core#58]
requesting BeautifulSoup (bs4) and lxml to be added to the cyhy-core image.

This will be to assist in scripts that need to perform web scraping, as it is a useful module to parse html results. 

There is an immediate need for this as I am developing a script to get a pulse on how a change from CVSS2 to CVSS3 would affect our Federal customer base in regards to BOD 18-01 and need to be able to both pull form the cyhy database and perform some web scraping.

lxml would also be nice, if it is not already included, as it has a lot of useful XML parsing utility and can be used as a parse for bs4 which is faster than the built-in html parser

**Comment by mcdonnnj** [comment]
The solution we'll look to implement will be a new requirements file that houses any Python package needed for the CyHy team's Docker image. We will also update the helper script so that the CyHy team will be able to easily create their own Docker images instead of having to rely on the dev team for support.
